config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :homes

  root to: "homes#index"

  namespace :api do
    resources :wishlist, only: [:create, :destroy]
  end

  resources :properties, only: [:show] do
    resources :bookings, only: [:new]
  end

  resources :booking_payments, only: [:create]

  get "booking_payments/success", to: "booking_payments#success"

  resources :wishlists, only: [:index]

  resource :profile, only: [:update, :edit]

  resource :password, only: [:update, :edit]

  resources :reservations, only: [:index] do
    resources :reviews, only: [:new, :create]
  end

  namespace :owner do
    resources :dashboard, only: [:index]
    resources :properties do
      member do
        patch 'update_amenities'
        delete 'remove_image'
        patch 'add_images'
      end
    end
    resources :reservations, only: [:index]
  end



  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "homes#index" # This is commented out since it's already defined above
end

app/models/property.rb
# Validates the property model for all its entries

class Property < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 50 }
  validates :headline, presence: true, length: { maximum: 500 }
  validates :description, presence: true, length: { maximum: 500 }
  validates :address_1, presence: true, length: { maximum: 500 }
  validates :city, presence: true, length: { maximum: 500 }
  validates :state, presence: true, length: { maximum: 500 }
  validates :country, presence: true, length: { maximum: 500 }

  monetize :price_cents, allow_nil: true

  has_many_attached :images

  has_many :reviews, dependent: :destroy

  has_many :wishlists, dependent: :destroy
  has_many :wishlisted_users, through: :wishlists, source: :user, dependent: :destroy

  has_many :reservations, dependent: :destroy
  has_many :reserved_users, through: :reservations, source: :user, dependent: :destroy

  has_rich_text :description

  has_many :property_amenities, dependent: :destroy
  has_many :amenities, through: :property_amenities, source: :amenity, dependent: :destroy

  has_many :payments, through: :reservations, dependent: :destroy


  def update_average_rating
    average_rating = reviews.average(:final_rating);
    update_column(:average_final_rating, average_rating)
  end

  def average_cleanliness_rating
    reviews.average(:cleanliness_rating)
  end

  def average_accuracy_rating
    reviews.average(:accuracy_rating)
  end

  def average_checkin_rating
    reviews.average(:checkin_rating)
  end

  def average_communication_rating
    reviews.average(:communication_rating)
  end

  def average_location_rating
    reviews.average(:location_rating)
  end

  def average_value_rating
    reviews.average(:value_rating)
  end




  def wishlisted_by?(user = nil)
    return if user.nil?

    wishlisted_users.include?(user)
  end

  def available_dates
    next_reservation = reservations.upcoming_reservations.first
    current_reservation = reservations.current_reservations.first

    if current_reservation.nil? && next_reservation.nil?
      Date.tomorrow.strftime('%e %b')..(Date.tomorrow + 30.days).strftime('%e %b')
    elsif current_reservation.nil?
      Date.tomorrow.strftime('%e %b')..next_reservation.checkin_date.strftime('%e %b')
    elsif next_reservation.nil?
      current_reservation.checkout_date.strftime('%e %b')..(Date.tomorrow + 30.days).strftime('%e %b')
    else
      current_reservation.checkout_date.strftime('%e %b')..next_reservation.checkin_date.strftime('%e %b')
    end
  end
end

app/controllers/owner/properties_controller.rb
module Owner
  class PropertiesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_property, only: [:edit, :update, :update_amenities, :remove_image, :add_images]


    def index
      @properties = current_user.properties
    end

    def new
      @property = Property.new
    end

    def create
      @property = current_user.properties.create!(property_params)
      redirect_to edit_owner_property_path, notice: 'Listing Added Successfully. Edit property to add Images'

    end


    def update
      if @property.update!(property_params)
        redirect_to edit_owner_property_path, notice: 'Property Details Updated Successfully'
      else
        redirect_back fallback_location: edit_Owner_property_path, alert: 'Failed to update property, Check again later'
      end
    end

    def update_amenities
      if @property.update!(amenities_params)
        redirect_to edit_owner_property_path, notice: 'Amenities Details Updated Successfully'
      else
        redirect_back fallback_location: edit_Owner_property_path, alert: 'Failed to Update Amenities, Check again later'
      end
    end

    def remove_image
      image = @property.images.find(params[:image_id])
      if image.destroy!
        redirect_to edit_owner_property_path, notice: 'Property Image Deleted Successfully'
      else
        redirect_back fallback_location: edit_Owner_property_path, alert: 'Failed to Delete Image, Check again later'
      end
    end

    def add_images
      @property.images.attach(params[:property][:images])
      redirect_to edit_owner_property_path, notice: 'Property images uploaded'
    end

    def destroy
      @property.destroy
      redirect_to owner_properties_path, alert: "#{@property.name} deleted successfully."
    end


    private

    def set_property
      @property = current_user.properties.find(params[:id])
    end

    def amenities_params
      params.require(:property).permit(emenity_ids)
    end

    def property_params
    params.require(:property).permit(
      :name,
      :price,
      :headline,
      :description,
      :address_1,
      :address_2,
      :city,
      :state,
      :country
    )
    end


  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def show
    @property = Property.includes(:reviews).find_by(id: params[:id])

    if @property
      @reviews = @property.reviews
      @amenities = @property.amenities
      @overall_rating_counts = @property.reviews.group('ROUND(final_rating)').count.transform_keys(&:to_i)
      @overall_rating_counts.default = 0

      upcoming_reservations = @property.reservations.upcoming_reservations
      if upcoming_reservations.exists?
        @blocked_dates = upcoming_reservations.pluck(:checkin_date, :checkout_date).map { |reservation| [reservation[0].to_s, reservation[1].to_s] }
      else
        @blocked_dates = []
      end
    else
      flash[:alert] = "Property not found."
      redirect_to root_path
    end
  end
end

app/views/properties/_amenities.html.erb
<div class="lg:col-span-2 lg:col-start-1 lg:pr-8">
  <!-- Description and details -->
  <div class="border-t border-gray-200 pt-10 mt-4">
    <h2 class="text-xl font-medium leading-6 text-gray-900">What this place offers</h2>

    <div class="mt-6 grid grid-cols-1 md:grid-cols-2">
      <% amenities.limit(8).each do|amenity| %>
        <div class="py-2 flex">

          <%= image_tag "amenity_icons/#{amenity.icon}", class:"w-6 h-6" %>
          <p class="ms-4 font-light"><%= amenity.name %></p>
        </div>
      <% end %>
    </div>

    <% if (amenities.count > 6) %>
      <button
        type="button"
        data-controller="amenities"
        data-action="click->amenities#toggleAmenitiesModal"
        class="mt-8 rounded-md bg-white px-4 py-3 text-sm font-medium text-gray-900 text-lg ring-1 ring-inset ring-black hover:bg-gray-50"
      >
        Show all <%= amenities.count %> amenities
      </button>
    <% end %>
  </div>
</div>

<%= render 'shared/modal', modalTriggerId: "amenities", content: 'properties/amenities_modal', content_params: {amenities: amenities} %>

app/views/properties/_amenities_modal.html.erb
<div>
  <button data-action="click->modal#toggleModal" type="button" class="relative rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
    <span class="absolute -inset-2.5"></span>
    <span class="sr-only">Close panel</span>
    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
    </svg>
  </button>
  <div class="py-6">
    <h2 class="text-xl font-medium leading-6 text-gray-900">What this place offers</h2>
    <div class="mt-6 divider">
      <% content_params[:amenities].limit(8).each do|amenity| %>
        <div class="py-4 flex">

          <%= image_tag "amenity_icons/#{amenity.icon}", class:"w-6 h-6" %>
          <p class="ms-4 font-light"><%= amenity.name %></p>
        </div>
        <div class="inset-0 flex items-center py-1" aria-hidden="true">
          <div class="w-full border-t border-gray-200"></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/properties/_description_modal.html.erb
<div>
  <button data-action="click->modal#toggleModal" type="button" class="relative rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
    <span class="absolute -inset-2.5"></span>
    <span class="sr-only">Close panel</span>
    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
    </svg>
  </button>
  <div class="py-6">
    <h2 class="text-xl font-medium leading-6 text-gray-900">About this place</h2>
    <p class="text-base text-gray-900 mt-6"><%= @property.description %></p>
  </div>
</div>

app/views/properties/_property_item.html.erb
<%= link_to property_path(property) do %>
  <div class="group relative cursor-pointer ">
    <div class="relative overflow-hidden rounded-md bg-gray-200">
      <div class="swiper">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
          <% property.images.each do |image| %>
            <%= image_tag image, class:"swiper-slide h-full w-full object-cover object-center lg:h-full lg:w-full" %>
          <% end %>
        </div>

        <%# TODO: Swiper buttons are not working %>
        <!-- If we need navigation buttons -->
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
      </div>

      <div class="absolute z-10 right-0 top-0 m-4">
        <svg xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 32 32"
          aria-hidden="true"
          role="presentation"
          focusable="false"
          class="block h-6 w-6 stroke-white stroke-2 <%= property.wishlisted_by?(current_user) ? 'fill-primary' : 'fill-none' %>"
          style="overflow: visible;"
          data-controller="wishlist"
          data-user-logged-in="<%= user_signed_in? %>"
          data-property-id="<%= property.id %>"
          data-user-id="<%= current_user&.id %>"
          data-wishlist-id="<%= property.wishlists.find_by(user: current_user)&.id %>"
          data-action="click->wishlist#updateWishlistStatus"
          data-wishlist-target="icon"
          data-status="<%= property.wishlisted_by?(current_user) %>"
          >
            <path d="M16 28c7-4.73 14-10 14-17a6.98 6.98 0 0 0-7-7c-1.8 0-3.58.68-4.95 2.05L16 8.1l-2.05-2.05a6.98 6.98 0 0 0-9.9 0A6.98 6.98 0 0 0 2 11c0 7 7 12.27 14 17z"></path>
        </svg>
      </div>
    </div>
    <div class="mt-2">
      <div class="flex justify-between">
        <h3 class="text-base font-medium text-gray-700 line-clamp-1">
          <%= property.city %>, <%= property.country %>
        </h3>
        <p class="flex items-center text-sm font-light">
          <svg
            class="mr-1 block w-3 h-3 fill-current"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 32 32"
            aria-hidden="true"
            role="presentation"
            focusable="false"
          >
            <path fill-rule="evenodd" d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z"></path>
          </svg>
          <% if property.reviews_count > 0 %>
            <%= property.average_final_rating.round(2) %> (<%= property.reviews_count %>)
          <% else %>
            New Listing
          <% end %>
        </p>
      </div>
      <%# TODO: Add distance from property based on location %>
      <% if minimal_details %>
        <p class="mt-0.5 text-sm text-gray-500"><%= property.bed_count %> beds</p>
      <% else %>
        <p class="mt-0.5 text-sm text-gray-500"><%= property.available_dates.first %> - <%= property.available_dates.last %></p>
        <p class="mt-0.5 text-sm font-light text-black">
          <span class="font-medium"><%= humanized_money_with_symbol(property.price) %></span> night
        </p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/properties/show.html.erb
<div class="bg-white">
  <main class="pt-4 pb-16">
    <!-- Headline + Share + Wishlist -->
    <div class="flex justify-between mx-auto max-w-2xl px-4 sm:px-6 lg:max-w-7xl lg:px-8 py-2">
      <h1 class="inline text-2xl font-medium leading-7 text-gray-900 sm:truncate"><%= @property.headline %></h1>
      <div class="space-x-1">
        <span
          data-controller="share"
          data-action="click->share#toggleShareModal"
          class="px-3 pt-2 pb-3 hover:rounded-md hover:bg-gray-100 cursor-pointer"
        >
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" aria-hidden="true" role="presentation" focusable="false" style="display: inline; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 2; overflow: visible;"><g fill="none"><path d="M27 18v9a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-9M16 3v23V3zM6 13l9.3-9.3a1 1 0 0 1 1.4 0L26 13"></path></g></svg>
          <span class="underline text-sm ms-1">Share</span>
        </span>

        <span
          class="px-3 pt-2 pb-3 hover:rounded-md hover:bg-gray-100 cursor-pointer"
          data-controller="wishlist"
          data-user-logged-in="<%= user_signed_in? %>"
          data-property-id="<%= @property.id %>"
          data-user-id="<%= current_user&.id %>"
          data-wishlist-id="<%= @property.wishlists.find_by(user: current_user)&.id %>"
          data-action="click->wishlist#updateWishlistStatus"
          data-status="<%= @property.wishlisted_by?(current_user) %>"
        >
          <svg xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 32 32"
            aria-hidden="true"
            role="presentation"
            focusable="false"
            class="inline h-4 w-4 stroke-black stroke-2 <%= @property.wishlisted_by?(current_user) ? 'fill-primary' : 'fill-none' %>"
            style="overflow: visible;"
            data-wishlist-target="icon"
            >
              <path d="M16 28c7-4.73 14-10 14-17a6.98 6.98 0 0 0-7-7c-1.8 0-3.58.68-4.95 2.05L16 8.1l-2.05-2.05a6.98 6.98 0 0 0-9.9 0A6.98 6.98 0 0 0 2 11c0 7 7 12.27 14 17z"></path>
          </svg>
          <span
            class="underline text-sm ms-1"
            data-wishlist-target="text"
          >
            <%= @property.wishlisted_by?(current_user) ? 'Saved' : 'Save' %>
          </span>
        </span>
      </div>
    </div>
    <!-- Image gallery -->
    <% if @property.images.present? %>
      <div class="mx-auto mt-6 max-w-2xl sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-4 lg:gap-x-2 lg:px-8">
        <% if @property.images.count < 5 %>
          <div class="aspect-h-2 aspect-w-6 overflow-hidden lg:rounded-lg lg:block col-span-4">
          <%= image_tag @property.images[0], class:"h-full w-full object-cover object-center" %>
        </div>
        <% else %>
          <div class="aspect-h-2 aspect-w-3 overflow-hidden lg:rounded-l-lg lg:block col-span-2">
              <%= image_tag @property.images[0], class:"h-full w-full object-cover object-center" %>
            </div>
            <div class="hidden lg:grid lg:grid-cols-1 lg:gap-y-2">
              <div class="aspect-h-2 aspect-w-3 overflow-hidden">
                <%= image_tag @property.images[1], class:"h-full w-full object-cover object-center" %>
              </div>
              <div class="aspect-h-2 aspect-w-3 overflow-hidden">
                <%= image_tag @property.images[2], class:"h-full w-full object-cover object-center" %>
              </div>
            </div>
            <div class="hidden lg:grid lg:grid-cols-1 lg:gap-y-2">
              <div class="aspect-h-2 aspect-w-3 overflow-hidden rounded-tr-lg">
                <%= image_tag @property.images[3], class:"h-full w-full object-cover object-center" %>
              </div>
              <div class="aspect-h-2 aspect-w-3 overflow-hidden rounded-br-lg">
                <%= image_tag @property.images[4], class:"h-full w-full object-cover object-center" %>
              </div>
            </div>
          </div>
        <% end %>
    <% else %>
      <div class="aspect-h-2 aspect-w-6 overflow-hidden lg:rounded-lg lg:block col-span-4">
        <svg width="640" height="480" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"></svg>
      </div>

    <% end %>
    <!-- Property info -->
    <div class="mx-auto max-w-2xl px-4 pt-8 sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-3 lg:grid-rows-[auto,auto,1fr] lg:gap-x-8 lg:px-8">
      <!-- Name + Description -->
      <div class="lg:col-span-2 lg:pr-8">
        <h2 class="text-xl font-medium leading-6 text-gray-900 sm:truncate"><%= @property.name %>, <%= @property.country %></h2>
        <div class="mt-1 font-light">
          <%# TODO: Add checks: check if any value is 0 or 1 or more than 1 %>
          <%= @property.guest_count %> guests · <%= @property.bedroom_count %> bedrooms · <%= @property.bed_count %> beds · <%= @property.bathroom_count %> bathrooms
        </div>
        <div class="mt-1 flex text-base items-center">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 32 32"
            aria-hidden="true"
            role="presentation"
            focusable="false"
            class="me-1"
            style="display: inline; height: 16px; width: 16px; fill: currentcolor;"
          >
            <path fill-rule="evenodd" d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z"></path>
          </svg>
          <% if @property.reviews_count != 0 %>
            <span class="font-medium"><%= (@property.average_final_rating).round(2) %> · <span class="underline"><%= @property.reviews_count %> reviews</span> </span>
          <% else %>
            <span class="font-light">No reviews yet</span>
          <% end %>
        </div>

        <!-- Description and details -->
        <div class="border-t border-gray-200 pt-10 mt-4 mb-8">
          <h3 class="sr-only">Description</h3>

          <div class="space-y-6">
            <p class="text-base text-gray-900"><%= @property.description.to_plain_text.truncate(400) %></p>
            <% if @property.description.to_plain_text.length > 400 %>
              <div
                class="flex items-center gap-1"
                data-controller="description"
                data-action="click->description#toggleDescriptionModal"
              >
                <span class="font-medium underline">Show more</span>
                <svg viewBox="0 0 18 18" role="presentation" aria-hidden="true" focusable="false" style="height: 12px; width: 12px; display: block; fill: var(--f-k-smk-x);"><path d="m4.29 1.71a1 1 0 1 1 1.42-1.41l8 8a1 1 0 0 1 0 1.41l-8 8a1 1 0 1 1 -1.42-1.41l7.29-7.29z" fill-rule="evenodd"></path></svg>
              </div>

              <%= render 'shared/modal', modalTriggerId: "description", content: 'properties/description_modal', content_params: {description: @property.description} %>
            <% end %>
          </div>
        </div>

        <!-- Amenities -->
        <%= render :partial => 'properties/amenities', :locals => {:amenities => @property.amenities} %>
      </div>

      <!-- Booking Component -->
      <div
        class="mt-4 lg:mt-0 border rounded-xl p-6 shadow-xl h-min"
        data-controller="booking"
        data-per-night-price="<%= humanized_money(@property.price) %>"
        data-blocked-dates="<%= @blocked_dates %>"
        >
        <h2 class="sr-only">Booking information</h2>
        <p class="text-lg font-light tracking-tight text-gray-900"><span class="text-2xl font-semibold"><%= humanized_money_with_symbol(@property.price) %></span> night</p>
        <div class="flex mt-6">
          <div class="rounded-l-lg px-3 pb-1.5 pt-2.5 shadow-sm ring-1 ring-inset ring-gray-400 focus-within:ring-2 focus-within:ring-indigo-600">
            <label for="checkin" class="block text-xs font-medium text-gray-900">CHECK-IN</label>
            <input
              type="text"
              name="checkin"
              id="checkin"
              class="block w-full border-0 p-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6"
              value="<%= Date.tomorrow.strftime('%Y-%m-%d') %>"
              data-booking-target="checkin"
              >
          </div>

          <div class="rounded-r-lg px-3 pb-1.5 pt-2.5 shadow-sm ring-1 ring-inset ring-gray-400 focus-within:ring-2 focus-within:ring-indigo-600">
            <label for="checkout" class="block text-xs font-medium text-gray-900">CHECK-OUT</label>
            <input
              type="text"
              name="checkout"
              id="checkout"
              class="block w-full border-0 p-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6"
              value="<%= (Date.tomorrow + 1.day).strftime('%Y-%m-%d') %>"
              data-booking-target="checkout"
              >
          </div>

        </div>
        <button
          data-reserve-property-url="<%= new_property_booking_path(@property) %>"
          type="submit"
          data-action="click->booking#reserveProperty"
          class="mt-4 flex w-full items-center justify-center rounded-md border border-transparent bg-primary px-8 py-3 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
        >
          Reserve
        </button>
        <p class="font-light text-center text-sm py-4">You won't be charged yet</p>
        <div class="mt-4">
          <div class="flex justify-between font-light">
            <p><%= humanized_money_with_symbol(@property.price) %> x <span data-booking-target="numberOfNights">1</span> night</p>
            <p><%= currency_symbol %><span data-booking-target="baseFare">0</span></p>
          </div>
          <div class="flex justify-between font-light mt-4">
            <p>Airbnb service fee</p>
            <p><%= currency_symbol %><span data-booking-target="serviceFee">0</span></p>
          </div>
        </div>
        <div class="relative py-6">
          <div class="absolute inset-0 flex items-center" aria-hidden="true">
            <div class="w-full border-t border-gray-300"></div>
          </div>
        </div>
        <div class="flex justify-between font-medium">
          <p>Total</p>
          <p><%= currency_symbol %><span data-booking-target="totalAmount">0</span></p>
        </div>
      </div>
    </div>

    <!-- Reviews -->
    <%= render :partial => 'properties/reviews', :locals => {:property => @property} %>
  </main>
</div>

<%= render 'shared/modal', modalTriggerId: "share", content: 'properties/share_modal', content_params: { property: @property } %>