config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :homes

  root to: "homes#index"

  namespace :api do
    resources :wishlist, only: [:create, :destroy]
  end

  resources :properties, only: [:show] do
    resources :bookings, only: [:new]
  end

  resources :booking_payments, only: [:create]

  get "booking_payments/success", to: "booking_payments#success"

  resources :wishlists, only: [:index]

  resource :profile, only: [:update, :edit]

  resource :password, only: [:update, :edit]

  resources :reservations, only: [:index] do
    resources :reviews, only: [:new, :create]
  end

  namespace :owner do
    resources :dashboard, only: [:index]
    resources :properties do
      member do
        patch 'update_amenities'
        delete 'remove_image'
        patch 'add_images'
      end
    end
    resources :reservations, only: [:index]
  end



  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "homes#index" # This is commented out since it's already defined above
end

app/models/property.rb
# Validates the property model for all its entries

class Property < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 50 }
  validates :headline, presence: true, length: { maximum: 500 }
  validates :description, presence: true, length: { maximum: 500 }
  validates :address_1, presence: true, length: { maximum: 500 }
  validates :city, presence: true, length: { maximum: 500 }
  validates :state, presence: true, length: { maximum: 500 }
  validates :country, presence: true, length: { maximum: 500 }

  monetize :price_cents, allow_nil: true

  has_many_attached :images

  has_many :reviews, dependent: :destroy

  has_many :wishlists, dependent: :destroy
  has_many :wishlisted_users, through: :wishlists, source: :user, dependent: :destroy

  has_many :reservations, dependent: :destroy
  has_many :reserved_users, through: :reservations, source: :user, dependent: :destroy

  has_rich_text :description

  has_many :property_amenities, dependent: :destroy
  has_many :amenities, through: :property_amenities, source: :amenity, dependent: :destroy

  has_many :payments, through: :reservations, dependent: :destroy


  def update_average_rating
    average_rating = reviews.average(:final_rating);
    update_column(:average_final_rating, average_rating)
  end

  def average_cleanliness_rating
    reviews.average(:cleanliness_rating)
  end

  def average_accuracy_rating
    reviews.average(:accuracy_rating)
  end

  def average_checkin_rating
    reviews.average(:checkin_rating)
  end

  def average_communication_rating
    reviews.average(:communication_rating)
  end

  def average_location_rating
    reviews.average(:location_rating)
  end

  def average_value_rating
    reviews.average(:value_rating)
  end




  def wishlisted_by?(user = nil)
    return if user.nil?

    wishlisted_users.include?(user)
  end

  def available_dates
    next_reservation = reservations.upcoming_reservations.first
    current_reservation = reservations.current_reservations.first

    if current_reservation.nil? && next_reservation.nil?
      Date.tomorrow.strftime('%e %b')..(Date.tomorrow + 30.days).strftime('%e %b')
    elsif current_reservation.nil?
      Date.tomorrow.strftime('%e %b')..next_reservation.checkin_date.strftime('%e %b')
    elsif next_reservation.nil?
      current_reservation.checkout_date.strftime('%e %b')..(Date.tomorrow + 30.days).strftime('%e %b')
    else
      current_reservation.checkout_date.strftime('%e %b')..next_reservation.checkin_date.strftime('%e %b')
    end
  end
end

app/controllers/owner/dashboard_controller.rb
module Owner
  class DashboardController < ApplicationController
    before_action :authenticate_user!

    def index
      
    end
  end

end

app/controllers/owner/properties_controller.rb
module Owner
  class PropertiesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_property, only: [:edit, :update, :update_amenities, :remove_image, :add_images]


    def index
      @properties = current_user.properties
    end

    def new
      @property = Property.new
    end

    def create
      @property = current_user.properties.create!(property_params)
      redirect_to edit_owner_property_path, notice: 'Listing Added Successfully. Edit property to add Images'

    end


    def update
      if @property.update!(property_params)
        redirect_to edit_owner_property_path, notice: 'Property Details Updated Successfully'
      else
        redirect_back fallback_location: edit_Owner_property_path, alert: 'Failed to update property, Check again later'
      end
    end

    def update_amenities
      if @property.update!(amenities_params)
        redirect_to edit_owner_property_path, notice: 'Amenities Details Updated Successfully'
      else
        redirect_back fallback_location: edit_Owner_property_path, alert: 'Failed to Update Amenities, Check again later'
      end
    end

    def remove_image
      image = @property.images.find(params[:image_id])
      if image.destroy!
        redirect_to edit_owner_property_path, notice: 'Property Image Deleted Successfully'
      else
        redirect_back fallback_location: edit_Owner_property_path, alert: 'Failed to Delete Image, Check again later'
      end
    end

    def add_images
      @property.images.attach(params[:property][:images])
      redirect_to edit_owner_property_path, notice: 'Property images uploaded'
    end

    def destroy
      @property.destroy
      redirect_to owner_properties_path, alert: "#{@property.name} deleted successfully."
    end


    private

    def set_property
      @property = current_user.properties.find(params[:id])
    end

    def amenities_params
      params.require(:property).permit(emenity_ids)
    end

    def property_params
    params.require(:property).permit(
      :name,
      :price,
      :headline,
      :description,
      :address_1,
      :address_2,
      :city,
      :state,
      :country
    )
    end


  end

end

app/controllers/owner/reservations_controller.rb
module Owner
  class ReservationsController < ApplicationController
    before_action :authenticate_user!
    def index
      @reservations = current_user.reservations
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def show
    @property = Property.includes(:reviews).find_by(id: params[:id])

    if @property
      @reviews = @property.reviews
      @amenities = @property.amenities
      @overall_rating_counts = @property.reviews.group('ROUND(final_rating)').count.transform_keys(&:to_i)
      @overall_rating_counts.default = 0

      upcoming_reservations = @property.reservations.upcoming_reservations
      if upcoming_reservations.exists?
        @blocked_dates = upcoming_reservations.pluck(:checkin_date, :checkout_date).map { |reservation| [reservation[0].to_s, reservation[1].to_s] }
      else
        @blocked_dates = []
      end
    else
      flash[:alert] = "Property not found."
      redirect_to root_path
    end
  end
end

app/views/owner/properties/edit.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">
  <%= render 'shared/owner_sidebar' %>

  <main>
    <div class="px-8 py-8 border rounded-md lg:flex-auto my-8">
      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900">Property Images</h2>
        <div class="mt-2 grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-1">
          <% @property.images.each do |image| %>
            <div class="relative w-40 h-40">
              <%= image_tag image, class:'w-40 h-40 object-cover' %>
              <%= button_to remove_image_owner_property_path(image_id: image.id), method: :delete, class:"absolute top-1 right-1 rounded-3xl p-1 bg-white opacity-50" do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                </svg>
              <% end %>
            </div>
          <% end %>
        </div>

        <%= form_with model: @property, url: add_images_owner_property_path, class:'mt-6' do |f| %>
          <div>
            <div class="">
              <%= f.label 'Add Images', class:'block text-base font-semibold leading-7 text-gray-900 mb-2' %>
              <%= f.file_field :images, class:'font-medum', multiple: true %>
              <%= f.submit "Upload Images", class:"cursor-pointer mt-2 flex items-center justify-center rounded-md border border-transparent bg-primary px-8 py-2 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" %>
            </div>
          </div>
        <% end %>

      </div>
    </div>

    <div class="px-8 py-8 border rounded-md lg:flex-auto my-8">
      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900">Property Information</h2>

        <%= form_with model: @property, url: owner_property_path, class:'mt-6 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6' do |f| %>
          <div class="sm:col-span-3">
            <%= f.label :name, class:'block text-sm font-medium leading-6 text-gray-900' %>
            <%= f.text_field :name, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
          </div>

          <div class="sm:col-span-3">
            <%= f.label :price, class:'block text-sm font-medium leading-6 text-gray-900' %>
            <%= f.text_field :price, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
          </div>

          <div class="col-span-full">
            <%= f.label :headline, class:'block text-sm font-medium leading-6 text-gray-900' %>
            <%= f.rich_text_area :headline, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
          </div>

          <div class="col-span-full">
            <%= f.label :description, class:'block text-sm font-medium leading-6 text-gray-900' %>
            <%= f.rich_text_area :description, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
          </div>

          <div class="col-span-full">
            <%= f.label :address_1, class:'block text-sm font-medium leading-6 text-gray-900' %>
            <%= f.text_field :address_1, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
          </div>

          <div class="sm:col-span-4">
            <%= f.label :address_2, class:'block text-sm font-medium leading-6 text-gray-900' %>
            <%= f.text_field :address_2, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
          </div>

          <div class="sm:col-span-2">
            <%= f.label :city, class:'block text-sm font-medium leading-6 text-gray-900' %>
            <%= f.text_field :city, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
          </div>

          <div class="sm:col-span-2">
            <%= f.label :state, class:'block text-sm font-medium leading-6 text-gray-900' %>
            <%= f.text_field :state, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
          </div>

          <div class="sm:col-span-2">
            <%= f.label :country, class: 'block text-sm font-medium leading-6 text-gray-900' %>
            <%= f.country_select :country, {}, { class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' } %>
          </div>


          <%= f.submit "Save", class:"cursor-pointer mt-2 flex items-center justify-center rounded-md border border-transparent bg-primary px-8 py-3 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" %>

        <% end %>
      </div>
    </div>

    <div class="px-8 py-8 border rounded-md lg:flex-auto my-8">
      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900">Amenities</h2>

        <%= form_with model: @property, url: update_amenities_owner_property_path, class:'mt-6' do |f| %>
          <div class="mt-6 grid grid-cols-1 md:grid-cols-2">
            <% Amenity.all.each do|amenity| %>
              <div class="py-2 flex">
                <%= f.check_box :amenity_ids, {class: 'w-6 h-6 mr-2 rounded-md text-primary focus:ring-primary', multiple: :true}, amenity.id, nil  %>
                <%= image_tag "amenity_icons/#{amenity.icon}", class:"w-6 h-6" %>
                <%= f.label amenity.name, class:'ms-4 font-light' %>
              </div>
            <% end %>
          </div>

          <div class="col-span-full">
            <%= f.submit "Save", class:"cursor-pointer mt-2 flex items-center justify-center rounded-md border border-transparent bg-primary px-8 py-3 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="px-8 py-8 border border-red-500 rounded-md lg:flex-auto my-8">
      <div>
        <h2 class="text-2xl font-semibold leading-7 text-red-500">Delete Listing</h2>
        <p class="my-2">Are you sure you want to delete this listing?</p>
         <%= button_to 'Delete', owner_property_path, method: :delete, class:"mt-4 rounded p-1 bg-red-500 hover:bg-red-700 text-white px-8 py-2" %>
      </div>
    </div>
  </main>
</div>

app/views/owner/properties/index.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">
  <%= render 'shared/owner_sidebar' %>

  <main class="px-8 my-8 lg:flex-auto">
    <div>
      <div class="flex justify-between items-center">
        <h2 class="text-2xl font-semibold leading-7 text-gray-900">Properties</h2>
        <%= link_to 'Add Listing', new_owner_property_path, class:'cursor-pointer mt-2 flex items-center justify-center rounded-md border border-transparent bg-primary px-8 py-2 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2' %>
      </div>
      <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:gap-x-8">
        <% @properties.each do |property| %>
          <div class="flex flex-col">
            <%= render 'properties/property_item', property: property, minimal_details: false %>
            <%= link_to 'Edit', edit_owner_property_path(property), class:'cursor-pointer mt-2 flex items-center justify-center rounded-md border border-primary text-primary px-8 py-2 text-base font-medium hover:text-white hover:bg-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2' %>
          </div>
        <% end %>
      </div>
    </div>
  </main>
</div>

app/views/owner/properties/new.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">
  <%= render 'shared/owner_sidebar' %>

  <main>

    <div class="px-8 py-8 border rounded-md lg:flex-auto my-8">
  <div>
    <h2 class="text-base font-semibold leading-7 text-gray-900">Property Information</h2>

    <%= form_with model: @property, url: owner_properties_path, class:'mt-6 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6' do |f| %>
      <div class="sm:col-span-3">
        <%= f.label :name, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :name, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>

      <div class="sm:col-span-3">
        <%= f.label :price, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :price, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>

      <div class="col-span-full">
        <%= f.label :headline, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.rich_text_area :headline, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>

      <div class="col-span-full">
        <%= f.label :description, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.rich_text_area :description, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>

      <div class="col-span-full">
        <%= f.label :address_1, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :address_1, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>

      <div class="sm:col-span-3">
        <%= f.label :address_2, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :address_2, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>

      <div class="sm:col-span-3">
        <%= f.label :city, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :city, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>

      <div class="sm:col-span-3">
        <%= f.label :state, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :state, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>

      <div class="sm:col-span-3">
            <%= f.label :country, class: 'block text-sm font-medium leading-6 text-gray-900' %>
            <%= f.country_select :country, {}, { class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' } %>
      </div>


        <%= f.submit "Save", class:"cursor-pointer mt-2 col-span-full flex items-center justify-center rounded-md border border-transparent bg-primary px-8 py-3 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" %>

    <% end %>
  </div>
</div>

  </main>
</div>