config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :homes

  root to: "homes#index"

  namespace :api do
    resources :wishlist, only: [:create, :destroy]
  end

  resources :properties, only: [:show] do
    resources :bookings, only: [:new]
  end

  resources :booking_payments, only: [:create]

  get "booking_payments/success", to: "booking_payments#success"

  resources :wishlists, only: [:index]

  resource :profile, only: [:update, :edit]

  resource :password, only: [:update, :edit]

  resources :reservations, only: [:index] do
    resources :reviews, only: [:new, :create]
  end

  namespace :owner do
    resources :dashboard, only: [:index]
    resources :properties do
      member do
        patch 'update_amenities'
        delete 'remove_image'
        patch 'add_images'
      end
    end
    resources :reservations, only: [:index]
  end



  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "homes#index" # This is commented out since it's already defined above
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_reservation, only: [:new, :create]

  def create
    data_params = review_params.merge(
      property_id: @reservation.property_id,
      reservation_id: @reservation.id
    )
    @review = current_user.reviews.new(data_params)

    if @review.save
      redirect_to root_path, notice: 'Review added successfully to the Property'
    else
      redirect_back fallback_location: root_path, alert: 'Failed to add review, Check again later'
    end
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:reservation_id])
  end

  def review_params
    params.permit(

      :content,
      :cleanliness_rating,
      :accuracy_rating,
      :checkin_rating,
      :communication_rating,
      :location_rating,
      :value_rating
    )
  end
end

app/views/reviews/_rating_item.html.erb
<div class="flex justify-between py-4">
  <%= f.label category_rating, class:'text-sm font-medium leading-6 text-gray-900' %>

  <div class="flex">
    <%= f.hidden_field category_rating, data: {"rating-target": category_rating} %>
    <% 5.times do |i| %>
      <svg
        class="fill-gray-300 h-6 w-6 flex-shrink-0 cursor-pointer"
        viewBox="0 0 20 20"
        fill="currentColor"
        aria-hidden="true"
        data-action="click->rating#setRating"
        data-category="<%= category_rating %>"
        data-rating="<%= i + 1 %>"
        data-rating-target="star"
      >
        <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
      </svg>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">
  <main class="px-8 my-8 lg:flex-auto">
    <div>
      <h2 class="text-2xl font-semibold leading-7 text-gray-900">Add Review</h2>
    </div>

    <div class="mt-4 border border-gray-300 rounded-xl p-6 h-min">
      <div class="flex justify-between">
        <div class="flex items-center">
          <%= image_tag @reservation.property.images[0], class:"w-24 h-24 object-cover rounded-md"%>
          <div class="ml-3 text-black font-medium">
            <div class=><%= @reservation.property.name %> - <%= @reservation.property.city %>, <%= @reservation.property.state %></div>
            <span class="inline-flex items-center pointer-events-none block text-sm text-black mt-2">
              <svg class="mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" aria-hidden="true" role="presentation" focusable="false" style="display: block; height: 12px; width: 12px; fill: currentcolor;">
                <path fill-rule="evenodd" d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z"></path>
              </svg>
              <%= @reservation.property.average_final_rating.round(2) %> (<%= @reservation.property.reviews_count %> reviews)
            </span>
          </div>
        </div>
      </div>

      <div class="relative py-6">
        <div class="absolute inset-0 flex items-center" aria-hidden="true">
          <div class="w-full border-t border-gray-300"></div>
        </div>
      </div>

      <div class="max-w-96">
        <%= form_with url: reservation_reviews_path() do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :property_id, value: @reservation.property_id %>

          <div class="flex flex-col py-4">
            <%= f.label :content, class:'block text-sm font-medium leading-6 text-gray-900' %>
            <%= f.text_area :content, class:'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
          </div>

          <div data-controller="rating">
            <%= render :partial => 'reviews/rating_item', :locals => {:f => f, category_rating: "cleanliness_rating"} %>
            <%= render :partial => 'reviews/rating_item', :locals => {:f => f, category_rating: "accuracy_rating"} %>
            <%= render :partial => 'reviews/rating_item', :locals => {:f => f, category_rating: "checkin_rating"} %>
            <%= render :partial => 'reviews/rating_item', :locals => {:f => f, category_rating: "communication_rating"} %>
            <%= render :partial => 'reviews/rating_item', :locals => {:f => f, category_rating: "location_rating"} %>
            <%= render :partial => 'reviews/rating_item', :locals => {:f => f, category_rating: "value_rating"} %>
          </div>

          <%= f.submit "Submit Review", class:"cursor-pointer mt-4 flex items-center justify-center rounded-md border border-transparent bg-primary px-8 py-3 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" %>
        <% end %>
      </div>

    </div>
  </main>
</div>